### ISSUE TITLE
Plugin Installation error

### ISSUE THREAD

**Issue by kiran009** [phlegx/redmine_gitlab_hook#15]
rake aborted!
SyntaxError: /var/www/redmine/plugins/redmine_gitlab_hook/init.rb:11: syntax error, unexpected ':', expecting kEND
  settings default: {all_branches: 'yes',prune: '...
                   ^
/var/www/redmine/plugins/redmine_gitlab_hook/init.rb:11: odd number list for Hash
...ttings default: {all_branches: 'yes',prune: 'yes' },partial:...
                              ^
/var/www/redmine/plugins/redmine_gitlab_hook/init.rb:11: syntax error, unexpected ',', expecting kEND
...default: {all_branches: 'yes',prune: 'yes' },partial: 'setti...
                              ^
/var/www/redmine/plugins/redmine_gitlab_hook/init.rb:11: syntax error, unexpected '}', expecting kEND
...branches: 'yes',prune: 'yes' },partial: 'settings/gitlab_set...
                              ^
/var/www/redmine/lib/redmine/plugin.rb:133:in `load'
/var/www/redmine/lib/redmine/plugin.rb:124:in `each'
/var/www/redmine/lib/redmine/plugin.rb:124:in `load'
/var/www/redmine/config/initializers/30-redmine.rb:19
/var/www/redmine/config/environment.rb:14
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by phlegx** [comment]
Which Redmine version are you using?

**Comment by kiran009** [comment]
I'm not using Ruby version 1.8 instead using:
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]

I'have installed version v0.1.2 it gives the similar error as follows:
rake aborted!
SyntaxError: /var/www/redmine/plugins/redmine_gitlab_hook-0.1.2/init.rb:11: syntax error, unexpected ':', expecting kEND
  settings default: { all_branches: 'yes', prune:...
                   ^
/var/www/redmine/plugins/redmine_gitlab_hook-0.1.2/init.rb:11: odd number list for Hash
...tings default: { all_branches: 'yes', prune: 'yes' }, partia...
                              ^
/var/www/redmine/plugins/redmine_gitlab_hook-0.1.2/init.rb:11: syntax error, unexpected ',', expecting kEND
...efault: { all_branches: 'yes', prune: 'yes' }, partial: 'set...
                              ^
/var/www/redmine/plugins/redmine_gitlab_hook-0.1.2/init.rb:11: syntax error, unexpected '}', expecting kEND
...ranches: 'yes', prune: 'yes' }, partial: 'settings/gitlab_se...
                              ^
/var/www/redmine/lib/redmine/plugin.rb:133:in `load'
/var/www/redmine/lib/redmine/plugin.rb:124:in `each'
/var/www/redmine/lib/redmine/plugin.rb:124:in `load'
/var/www/redmine/config/initializers/30-redmine.rb:19
/var/www/redmine/config/environment.rb:14
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
