### ISSUE TITLE
undefined local variable or method `origin'

### ISSUE THREAD

**Issue by superbiche** [phlegx/redmine_gitlab_hook#16]
Hi,

I've followed the installation guidelines, but when I test my hook with Curl, I'm getting this error in Redmine's production.log. Below is the content of the error : 

    Started POST "/gitlab_hook" for 127.0.0.1 at 2015-02-20 11:02:58 +0100
    Processing by GitlabHookController#index as */*
      Parameters: {"project_id"=>"XXXXXXX", "key"=>"XXXXX"}
    Completed 500 Internal Server Error in 121.2ms

    NameError (undefined local variable or method `origin' for #<GitlabHookController:0x0000000479a8e8>):
      plugins/redmine_gitlab_hook/app/controllers/gitlab_hook_controller.rb:80:in `update_repository'
      plugins/redmine_gitlab_hook/app/controllers/gitlab_hook_controller.rb:18:in `block in index'
      plugins/redmine_gitlab_hook/app/controllers/gitlab_hook_controller.rb:16:in `each'
      plugins/redmine_gitlab_hook/app/controllers/gitlab_hook_controller.rb:16:in `index'
      actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
      actionpack (3.2.21) lib/abstract_controller/base.rb:167:in `process_action'
      actionpack (3.2.21) lib/action_controller/metal/rendering.rb:10:in `process_action'
      actionpack (3.2.21) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
      activesupport (3.2.21) lib/active_support/callbacks.rb:403:in `_run__771250421265358727__process_action__2082821875956202573__callbacks'
      activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
      activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
      activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
      actionpack (3.2.21) lib/abstract_controller/callbacks.rb:17:in `process_action'
      actionpack (3.2.21) lib/action_controller/metal/rescue.rb:29:in `process_action'
      actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
      activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
      activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
      activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
      actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
      actionpack (3.2.21) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
      activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
      actionpack (3.2.21) lib/abstract_controller/base.rb:121:in `process'
      actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
      actionpack (3.2.21) lib/action_controller/metal.rb:203:in `dispatch'
      actionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
      actionpack (3.2.21) lib/action_controller/metal.rb:246:in `block in action'
      actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `call'
      actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
      actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call'
      journey (1.0.4) lib/journey/router.rb:68:in `block in call'
      journey (1.0.4) lib/journey/router.rb:56:in `each'
      journey (1.0.4) lib/journey/router.rb:56:in `call'
      actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call'
      rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
      request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
      actionpack (3.2.21) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
      rack (1.4.5) lib/rack/etag.rb:23:in `call'
      rack (1.4.5) lib/rack/conditionalget.rb:35:in `call'
      actionpack (3.2.21) lib/action_dispatch/middleware/head.rb:14:in `call'
      actionpack (3.2.21) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
      actionpack (3.2.21) lib/action_dispatch/middleware/flash.rb:242:in `call'
      rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
      rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
      actionpack (3.2.21) lib/action_dispatch/middleware/cookies.rb:341:in `call'
      activerecord (3.2.21) lib/active_record/query_cache.rb:64:in `call'
      activerecord (3.2.21) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
      actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
      activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `_run__3639585918971082184__call__1327077786857334054__callbacks'
      activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
      activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
      activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
      actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
      actionpack (3.2.21) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
      actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
      actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
      railties (3.2.21) lib/rails/rack/logger.rb:32:in `call_app'
      railties (3.2.21) lib/rails/rack/logger.rb:16:in `block in call'
      activesupport (3.2.21) lib/active_support/tagged_logging.rb:22:in `tagged'
      railties (3.2.21) lib/rails/rack/logger.rb:16:in `call'
      actionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in `call'
      rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
      rack (1.4.5) lib/rack/runtime.rb:17:in `call'
      activesupport (3.2.21) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
      rack (1.4.5) lib/rack/lock.rb:15:in `call'
      actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
      rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
      rack-cache (1.2) lib/rack/cache/context.rb:143:in `pass'
      rack-cache (1.2) lib/rack/cache/context.rb:155:in `invalidate'
      rack-cache (1.2) lib/rack/cache/context.rb:71:in `call!'
      rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
      railties (3.2.21) lib/rails/engine.rb:484:in `call'
      railties (3.2.21) lib/rails/application.rb:231:in `call'
      railties (3.2.21) lib/rails/railtie/configurable.rb:30:in `method_missing'
      /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
      /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
      /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
      /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'

This error seems logical as in plugins/redmine_gitlab_hook/app/controllers/gitlab_hook_controller.rb, the update_repository method tries to use 'origin' but this one doesn't seem to exist (I don't know Ruby so maybe I'm wrong) : 

    # redmine_gitlab_hook/app/controllers/gitlab_hook_controller.rb, line 80
    command = git_command("fetch#{origin} origin", repository)

I temporarily activated the "All branches" option in the plugin options, and now the response from Curl is "OK".

**Comment by phlegx** [comment]
Version 0.1.2 solves the problem. Thx for the bug report!
