### ISSUE TITLE
Plugin Installation Error

### ISSUE THREAD

**Issue by kiran009** [phlegx/redmine_gitlab_hook#17]
I'm using Ruby version 2.1
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]

I'have installed version v0.1.2 it gives error as follows:
rake aborted!
SyntaxError: /var/www/redmine/plugins/redmine_gitlab_hook-0.1.2/init.rb:11: syntax error, unexpected ':', expecting kEND
settings default: { all_branches: 'yes', prune:...
^
/var/www/redmine/plugins/redmine_gitlab_hook-0.1.2/init.rb:11: odd number list for Hash
...tings default: { all_branches: 'yes', prune: 'yes' }, partia...
^
/var/www/redmine/plugins/redmine_gitlab_hook-0.1.2/init.rb:11: syntax error, unexpected ',', expecting kEND
...efault: { all_branches: 'yes', prune: 'yes' }, partial: 'set...
^
/var/www/redmine/plugins/redmine_gitlab_hook-0.1.2/init.rb:11: syntax error, unexpected '}', expecting kEND
...ranches: 'yes', prune: 'yes' }, partial: 'settings/gitlab_se...
^
/var/www/redmine/lib/redmine/plugin.rb:133:in load' /var/www/redmine/lib/redmine/plugin.rb:124:ineach'
/var/www/redmine/lib/redmine/plugin.rb:124:in `load'
/var/www/redmine/config/initializers/30-redmine.rb:19
/var/www/redmine/config/environment.rb:14
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by phlegx** [comment]
See new version 0.1.3: https://github.com/phlegx/redmine_gitlab_hook/tree/v0.1.3
