### ISSUE TITLE
Plugin Installation Error

### ISSUE THREAD

**Issue by kiran009** [phlegx/redmine_gitlab_hook#18]
I'm using Ruby version: ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux], getting the following error while installing the plugin:
It's now tried with v0.1.3 of the plugin.
An error occurred while loading the routes definition of redmine_gitlab_hook-0.1.3 plugin (/var/www/redmine/plugins/redmine_gitlab_hook-0.1.3/config/routes.rb): (eval):3: compile error
(eval):2: syntax error, unexpected ':', expecting kEND
  match 'gitlab_hook', to: 'gitlab_hook#index', via: [:get, :post]
                          ^
(eval):2: syntax error, unexpected ',', expecting kEND
  match 'gitlab_hook', to: 'gitlab_hook#index', via: [:get, :post]

**Comment by phlegx** [comment]
I don't know  why you get this errors. The following line is a valid ruby on rails line.

```match 'gitlab_hook', to: 'gitlab_hook#index', via: [:get, :post]```

So please give more information about your installation: Rails version, Redmine version,...

**Comment by phlegx** [comment]
I have updated tag v0.1.3. Please re-download and install.
