### ISSUE TITLE
WebHook - Redmine Error 500

### ISSUE THREAD

**Issue by BerndSchneider** [phlegx/redmine_gitlab_hook#19]
The WebHook is not working - I get an "Redmine Error 500". 

Redmine Version: Redmine 2.6.2.stable
Gitlab Version: GitLab 6.4.3

In GitLab 6.4.3 is no "Post-Receive URL" - so I added the URL into the "Push events" - Trigger. 
Is your plugin not compatible with this GitLab version?

Update: When I curl to send the POST, I get: "Git command failed on repository: [repository_name]!"

Thanks

**Comment by phlegx** [comment]
I need more information! Redmine server log (only about the 500 error). Add the URL on Web-Hooks -> Push events. Is the URL and the Redmine project id and key right?

**Comment by BerndSchneider** [comment]
Yes, the repository is shown in Redmine as expected.

I found the output of the Command in production.log, telling me "Permission denied" for  accessing FETCH_HEAD. 

GitLabHook: Command 'git --git-dir='/home/gitlab/repositories/myRep.git' fetch --all' didn't exit properly. Full output: ["error: cannot open /home/gitlab/repositories/myRepo.git/FETCH_HEAD: Permission denied\n", "\n"]
  Rendered text template (0.0ms)

So, it is a access rights problem I have to solve first.
