### ISSUE TITLE
hook message Page not found

### ISSUE THREAD

**Issue by kitsos** [phlegx/redmine_gitlab_hook#2]
<html>
<title>Redmine 404 error</title>

<style>
body{
font-family: Trebuchet MS,Georgia,"Times New Roman",serif;
color:#303030;
margin:10px;
}
h1{
font-size:1.5em;
}
p{
font-size:0.8em;
}
</style>

<body>
  <h1>Page not found</h1>
  <p>The page you were trying to access doesn't exist or has been removed.</p>
  <p><a href="javascript:history.back()">Back</a></p>
</body>
</html>

I am getting this error when i am doing the post receive. Is there any hint on what point i am doing something wrong. 

I follow all your instructions in Bitnami Redmine Stack. Have you ever try to run it in that installation? 
Any suggestion would be appreciated. 

Kind regards,
K.

**Comment by hubertchylik** [comment]
@phlegx , i have got additional problem with your plugin. I have installed and configured it properly, but it doesn't work. After going to webhook url, redmine gives error:

"Page not found
The page you were trying to access doesn't exist or has been removed."

Redmine user on the server is able to run git. I have turned WS in repositories, but still with no effect ;(

**Comment by Jellyfrog** [comment]
it only support POST requests, not GET..
Use curl or similar:
`curl 'http://redmine.server/gitlab_hook' -d 'project_id=[redmine-project-identifier]&key=[api-key]'`

**Comment by csersyadav** [comment]
same issue

**Comment by phlegx** [comment]
Can this post #20 solve your issue?

**Comment by estan** [comment]
@phlegx I'm in the same boat as some others here I think. Does the plugin not support Redmine installed under a URI prefix? (e.g. `/redmine`). If so, I can't use it because that's how Redmine is set up here, and I can't easily change this just to get this plugin working :/

**Comment by estan** [comment]
@phlegx Looking at my output from `RAILS_ENV=production rake routes`, I see:

```
.
.
.
                          sys_projects GET                /redmine/sys/projects(.:format)                                                           sys#projects
                                       POST               /redmine/sys/projects/:id/repository(.:format)                                            sys#create_project_repository
                  sys_fetch_changesets GET|POST           /redmine/sys/fetch_changesets(.:format)                                                   sys#fetch_changesets
                               uploads POST               /redmine/uploads(.:format)                                                                attachments#upload
                                       GET                /redmine/robots.txt(.:format)                                                             welcome#robots
                           gitlab_hook GET|POST           /gitlab_hook(.:format)                                                                    gitlab_hook#index
```

The path for the `gitlab_hook` is wrong, it should be `/redmine/gitlab_hook`. Will you fix the plugin to work with Redmine installations under a sub-URI?

**Comment by estan** [comment]
I was able to fix the problem locally I think, by enclosing the the `match` in `config/routes.rb` with a `scope` for the sub-URI that we use ("/redmine"):

```ruby
RedmineApp::Application.routes.draw do
  scope "/redmine" do
    match 'gitlab_hook', :to => 'gitlab_hook#index', :via => [:get, :post]
  end
end
```

**Comment by phlegx** [comment]
Hi @estan, your solution is correct but not dynamic. I cannot change it in the code. Some people uses Redmine with sub-URI and some not. So, we need a solution for both.

**Comment by estan** [comment]
@phlegx Yes, my change was of course just a local hack to get it to work for me. Would be better if it could be made dynamic of course.
