### ISSUE TITLE
Redmine Server Gitlab Hook not accessible

### ISSUE THREAD

**Issue by kiran009** [phlegx/redmine_gitlab_hook#20]
I have installed "redmine_gitlab_hook" but the URL is not accessible: https://redmine.mydomain.com/gitlab_hook. My redmine is running under apache.

**Comment by phlegx** [comment]
With so little information, it is impossible to give an answer that solves the problem.

**Comment by a88596a** [comment]
my case / no default prefix.
https://redmine.mydomain.com/ redmine / gitlab_hook
check. prefix.
