### ISSUE TITLE
Git command failed on repository

### ISSUE THREAD

**Issue by sw-dev1** [phlegx/redmine_gitlab_hook#24]
What is causing this error and how to resolve?

Thanks

**Comment by phlegx** [comment]
Please provide more information!

**Comment by sw-dev1** [comment]
The error is the response from Test Hook in Gitlab. The URL is in the form http://[redmine installation]/gitlab_hook?project_id=[Redmine project id]&key=[Redmine project key]. 
Here are the response headers from the RESTful debugger:

    Status Code: 406 Not Acceptable
    Cache-Control: no-cache
    Connection: close
    Content-Length: 49
    Content-Type: text/html; charset=utf-8
    Date: Wed, 02 Nov 2016 20:03:41 GMT
    Server: Apache
    Status: 406 Not Acceptable
    Vary: Cookie
    X-Powered-By: Phusion Passenger 5.0.6
    x-content-type-options: nosniff
    x-frame-options: SAMEORIGIN
    x-request-id: [id removed  ]
    x-runtime: 0.091244
    x-xss-protection: 1; mode=block

What other information would be needed to track down this error? Cheers.

**Comment by juan-cb** [comment]
If you are using git clone --mirror when creating the repository, try using the GIT URL with the user and password:

> git clone --mirror http://user:password@gitlab.server.xyz/user/repository.git 

Also, chown the path to repository.git to redmine:redmine user/group as this:

> chown -R redmine:redmine /path/to/repository.git

I solved the 406 issue with these fixes

**Comment by sw-dev1** [comment]
Thank you, looks that this solved it for me, too. In my setup - redmine bitnami stack on a VM - the user:group for chown is bitnami:daemon, just in case someone might have the same setup.

**Comment by vscodeenv** [comment]
> If you are using git clone --mirror when creating the repository, try using the GIT URL with the user and password:
> 
> > git clone --mirror http://user:password@gitlab.server.xyz/user/repository.git
> 
> Also, chown the path to repository.git to redmine:redmine user/group as this:
> 
> > chown -R redmine:redmine /path/to/repository.git
> 
> I solved the 406 issue with these fixes

git clone --mirror ssh://git@xxx.xxx.xxx.xx:xxxx/maker/scom/stm32g0xx/smartboot_stm32g0xx_vscode.git

chown -R redmine:redmine ./smartboot_stm32g0xx_vscode.git

If ssh is used, a permission problem is displayed! Can you help me see if there is anything else I need to pay attention to when using ssh?
