### ISSUE TITLE
Add support to use private repos

### ISSUE THREAD

**Issue by onegreyonewhite** [phlegx/redmine_gitlab_hook#26]
Could you add support for clone private repos?

**Comment by wraithbb** [comment]
With the current version it is possible. You just need some additional work to do it.
* Create access ssh key for your repository and put it somewhere on your redmine machine.
* Create a bash script to be used for GIT_SSH (gitlab_wrapper.sh). Don't forget to provide a valid path to your ssh key.
```sh
#!/bin/bash
ssh -i $DATA_DIR/mykeys/gitlab $1 $2
```

* In administration section of the plugin use *Git command prefix* field:
```sh
GIT_SSH=$GITLAB_WRAPPER_FOLDER/gitlab_wrapper.sh
```
