### ISSUE TITLE
Add option to use http url instead of ssh url

### ISSUE THREAD

**Issue by BrunoSpy** [phlegx/redmine_gitlab_hook#27]
Would it be possible to add an option to use git_http_url instead of git_ssh_url ?

https://github.com/phlegx/redmine_gitlab_hook/blob/master/app/controllers/gitlab_hook_controller.rb#L144

**Comment by phlegx** [comment]
@BrunoSpy  try out release v0.2.2 and please read the new documentation under Installation -> 3. and -> 4. There are some changes (Gitlab Web hook parameter `repository_git_url`).
