### ISSUE TITLE
Error 404  when configure

### ISSUE THREAD

**Issue by ejango** [phlegx/redmine_gitlab_hook#28]
After install redmine_gitlab_hook, when click in configure (Redmine plugin page) I get error 404:

In log I see:

Started GET "/settings/plugin/redmine_gitlab_hook" for 10.199.104.75 at 2016-12-01 11:16:22 -0200
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_gitlab_hook"}
  Current user: admin (id=1)
  Rendered settings/plugin.html.erb within layouts/admin (1.7ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.1ms)
Completed 404 Not Found in 27ms (Views: 11.2ms | ActiveRecord: 5.0ms)

I am using Redmine 3.3.0

**Comment by hnuzhoulin** [comment]
I face the same problem.
I install redmine using bitnami redmine installer in ubuntu.

**Comment by hnuzhoulin** [comment]
you can test this web_hook in restful tools using POST not GET.

**Comment by juan-cb** [comment]
Try to rename the plugin folder from /paht/redmine_gitlab_hook-0.1.3/ to /path/redmine_gitlab_hook/ and restart Redmine. 

I solved the same issue using it (also I changed the owner of the plugin to redmine:redmine)
