### ISSUE TITLE
Provide instructions for automated installation

### ISSUE THREAD

**Issue by FredrikWendt** [phlegx/redmine_gitlab_hook#31]
> As a system administrator,
> In order to eliminate human errors, enable automated testing at upgrades and enable full non-interactive automation,
> I would expect instructions on how to install and this plugin on to the official Docker images

I'm a Redmine newbie and I'm hoping to leverage GitLab, GitLab CI (and possibly GoCd) with Redmine to get close to a full Application Lifecycle Management stack which is fully Free Open Source Software based.

I understand the GitLab provided integration only makes "issue #123" like comments, link to redmine. There's no other mechanism. This plugin seems to solve part of this void.
https://docs.gitlab.com/ce/project_services/redmine.html

From what I understand, the instructions would be:

    FROM redmine:latest
    RUN cd /usr/src/redmine/plugins/ && \
        git clone --shallow https://github.com/phlegx/redmine_gitlab_hook.git && \
        bundle exec rake redmine:plugins:migrate RAILS_ENV=production

Anything I'm missing?

**Comment by phlegx** [comment]
Hi @FredrikWendt,

actually your Dockerfile and and the instructions look correct. It should work like that.

If you want to stick to a certain version (i.e. latest one is v0.1.3) you could download the zip archive like that:

```
RUN cd /usr/src/redmine/plugins/ && wget -O redmine_gitlab_hook.zip https://github.com/phlegx/redmine_gitlab_hook/archive/v0.1.3.zip
```

and unzip and rename/softlink  it. 

Checking out the corresponding git tag would also work.
