### ISSUE TITLE
plugin does not fetch any updates

### ISSUE THREAD

**Issue by fgrosswig** [phlegx/redmine_gitlab_hook#33]
i am not able to fetch any changes to the repository. we have setup it like described but no changes where submitted to the repository. How do we handle it?

Here my enviornment of redmine:
```
Environment:
  Redmine version                3.3.2.stable.16328
  Ruby version                   2.3.0-p0 (2015-12-25) [x86_64-linux]
  Rails version                  4.2.7.1
SCM:
  Git                            2.7.4
Redmine plugins:
  redmine_gitlab_hook            0.1.3
```
and Gitlab is at Version: GitLab CE 8.16.6

**Comment by phlegx** [comment]
There is no reaction for a long time on this issue. It will be closed.
