### ISSUE TITLE
Hook execution failed: getaddrinfo: Name or service not known

### ISSUE THREAD

**Issue by sw-dev1** [phlegx/redmine_gitlab_hook#34]
Gitlab webhook suddenly stopped working. A previously working setup now fails on test hook with "Hook execution failed: getaddrinfo: Name or service not known". Executing the same url with RESTClient works and redmine is updated.

Any ideas?

**Comment by phlegx** [comment]
So, if the execution works with RESTClient but not from Gitlab, it is not a `redmine_gitlab_hook` issue but a Gitlab server issue. It seams that the Gitlab server cannot resolve the redmine host.

**Comment by phlegx** [comment]
There is no reaction for a long time. It will be closed.
