### ISSUE TITLE
TypeError (Project 'project_name' ('project_id') repository not found with identifier ''

### ISSUE THREAD

**Issue by sw-dev1** [phlegx/redmine_gitlab_hook#40]
Probably relating to #38.
Hi, I am getting 
Project 'project_name' ('project_id') has no repository or repository not found with identifier ''.
The repository in Redmine does have an identifier. I changed it according to the instructions in the readme to be the same as 'project_id', but still getting the 500 error. 
In another setup this worked with the identifier = Redmine repository name (without the '.git')

Thx for your great work.

**Comment by fleeto** [comment]
The same issue

**Comment by phlegx** [comment]
@sw-dev1 @fleeto try out release v0.2.2 and please read the new documentation under Installation -> 3. and -> 4. There are some changes.
