### ISSUE TITLE
TypeError (Project 'DSMES' ('dsmes') has no repository or repository not found with identifier ''):

### ISSUE THREAD

**Issue by robinhli** [phlegx/redmine_gitlab_hook#41]
Redmine project Name: DSMES, identifier: dsmes.
Rep dir: /home/redmine/redmine-3.4.5/gitrepo/dsmes
rep identifier: dsmes

Environment:
  Redmine version                3.4.5.stable
  Ruby version                   2.0.0-p648 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.11
  Git                            1.7.1
  Filesystem                     
Redmine plugins:
  redmine_gitlab_hook            0.2.1

production.log:

same as #38?

Started POST "/gitlab_hook?project_id=dsmes&key=cH59MpLdvdCy2Yfk1dIF" for 192.168.31.83 at 2018-05-15 20:17:44 +0800
Processing by GitlabHookController#index as HTML
  Parameters: {"project_id"=>"dsmes", "key"=>"cH59MpLdvdCy2Yfk1dIF"}
Completed 500 Internal Server Error in 53ms (ActiveRecord: 6.9ms)

TypeError (Project 'DSMES' ('dsmes') has no repository or repository not found with identifier ''):
  plugins/redmine_gitlab_hook/app/controllers/gitlab_hook_controller.rb:131:in `find_repository'
  plugins/redmine_gitlab_hook/app/controllers/gitlab_hook_controller.rb:11:in `index'

**Comment by phlegx** [comment]
Please read the documentation:

4) In the project settings, activate “repository” module and add a new repository. Repository identifier is composed with {project_namespace}_{repository_name}. E.g. project name “test” in project namespace “business” with repository name “rails” results in “business_test_rails” as repository identifier. If no project namespace is used, use only the repository name. E.g. “rails”.

**Comment by phlegx** [comment]
@robinhli try out release v0.2.2 and please read the new documentation under Installation -> 3. and -> 4. There are some changes.

**Comment by robinhli** [comment]
YES.  I have read this.

But I don't understand what is the project name, what is the project namespace?

In Redmine system, my project homepage is:  http://192.168.31.100:7000/projects/dsmes, the project page show Name: DSMES, identifier: dsmes.

The repo is at: /home/redmine/redmine-3.4.5/gitrepo/dsmes


What identifier should I use for the repo? I tried dsmes, dsmes_dsmes, root_dsmes, but all fail.


BR
Robin


________________________________

**Comment by robinhli** [comment]
I Have upated the code 0.2.2(even though the redmine page still show 0.2.1)

It seems redmine can get the POST URL from gitlab, but I still not see the git updated at redmine. below is the log from httpd(redmine was configured under httpd)


Could you please help, thanks！


App 20855 output: "#<Repository::Git id: 3, project_id: 1, url: \"/home/redmine/redmine-3.4.5/gitrepo/dsmes\", login: \"\", password: \"\", root_url: \"/home/redmine/redmine-3.4.5/gitrepo/dsmes\", type: \"Repository::Git\", path_encoding: \"UTF-8\", log_encoding: nil, extra_info: {\"extra_report_last_commit\"=>\"0\", \"heads\"=>[\"941118779f26104b8e270e7635c5089301d07dd7\", \"a253463d08dba0e38030ddd0c4be427d0ed44f66\", \"92fbc2e1990d64762534ab6e9fdf224cca330b5c\"], \"db_consistent\"=>{\"ordering\"=>1}}, identifier: \"root_dsmes\", is_default: true, created_on: \"2018-05-15 12:17:09\">"
App 20372 output: "#<Repository::Git id: 3, project_id: 1, url: \"/home/redmine/redmine-3.4.5/gitrepo/dsmes\", login: \"\", password: \"\", root_url: \"/home/redmine/redmine-3.4.5/gitrepo/dsmes\", type: \"Repository::Git\", path_encoding: \"UTF-8\", log_encoding: nil, extra_info: {\"extra_report_last_commit\"=>\"0\", \"heads\"=>[\"941118779f26104b8e270e7635c5089301d07dd7\", \"a253463d08dba0e38030ddd0c4be427d0ed44f66\", \"92fbc2e1990d64762534ab6e9fdf224cca330b5c\"], \"db_consistent\"=>{\"ordering\"=>1}}, identifier: \"root_dsmes\", is_default: true, created_on: \"2018-05-15 12:17:09\">"




________________________________

**Comment by robinhli** [comment]
Hi, I have updated the code 0.2.2. (even it still show 0.2.1 at redmine)
and I still not see the repo updated automatically. When I setup the webhook at gitlab and test the URL, the log at redmine as follows:

Started POST "/gitlab_hook?project_id=dsmes&repository_name=dsmes&repository_namespace=root&key=cH59MpLdvdCy2Yfk1dIF" for 192.168.31.100 at 2018-05-22 19:35:48 +0800
Processing by GitlabHookController#index as HTML
  Parameters: {"object_kind"=>"push", "event_name"=>"push", "before"=>"5b1296dc25d625ce132599b0aef3b9c5f9a16733", "after"=>"8a5f1c470ded677563a97f3571787fa3f0fe2650", "ref"=>"refs/heads/master", "checkout_sha"=>"8a5f1c470ded677563a97f3571787fa3f0fe2650", "message"=>nil, "user_id"=>3, "user_name"=>"LI  Haibin", "user_username"=>"LIhaibin", "user_email"=>"lihaibin@dashu-tech.com", "user_avatar"=>"https://www.gravatar.com/avatar/231b2e7b3e7a5f348079b2d12a512105?s=80&d=identicon", "project_id"=>"dsmes", "project"=>{"id"=>11, "name"=>"dsmes", "description"=>"", "web_url"=>"http://192.168.31.100:9000/gitlab/root/dsmes", "avatar_url"=>nil, "git_ssh_url"=>"git@192.168.31.100:root/dsmes.git", "git_http_url"=>"http://192.168.31.100:9000/gitlab/root/dsmes.git", "namespace"=>"root", "visibility_level"=>0, "path_with_namespace"=>"root/dsmes", "default_branch"=>"master", "ci_config_path"=>nil, "homepage"=>"http://192.168.31.100:9000/gitlab/root/dsmes", "url"=>"git@192.168.31.100:root/dsmes.git", "ssh_url"=>"git@192.168.31.100:root/dsmes.git", "http_url"=>"http://192.168.31.100:9000/gitlab/root/dsmes.git"}, "commits"=>[{"id"=>"8a5f1c470ded677563a97f3571787fa3f0fe2650", "message"=>"Merge branch 'issue#1053' into 'master'\n\nissue#1053\n\nSee merge request root/dsmes!33", "timestamp"=>"2018-05-22T18:47:43+08:00", "url"=>"http://192.168.31.100:9000/gitlab/root/dsmes/commit/8a5f1c470ded677563a97f3571787fa3f0fe2650", "author"=>{"name"=>"LI  Haibin", "email"=>"lihaibin@dashu-tech.com"}, "added"=>nil, "modified"=>["prodcell/views.py"], "removed"=>nil}, {"id"=>"23c4d00715205034e6e682b87acdd08c6f67026d", "message"=>"issue#1053\n", "timestamp"=>"2018-05-22T18:46:09+08:00", "url"=>"http://192.168.31.100:9000/gitlab/root/dsmes/commit/23c4d00715205034e6e682b87acdd08c6f67026d", "author"=>{"name"=>"lihaibin", "email"=>"lihaibin@dashu-tech.com"}, "added"=>nil, "modified"=>["prodcell/views.py"], "removed"=>nil}, {"id"=>"5b1296dc25d625ce132599b0aef3b9c5f9a16733", "message"=>"Merge branch 'issue#1047' into 'master'\n\nissue#1047\n\nSee merge request root/dsmes!32", "timestamp"=>"2018-05-22T17:32:38+08:00", "url"=>"http://192.168.31.100:9000/gitlab/root/dsmes/commit/5b1296dc25d625ce132599b0aef3b9c5f9a16733", "author"=>{"name"=>"Fei Daren", "email"=>"feidaren@dashu-tech.com"}, "added"=>nil, "modified"=>["prodcell/viewsZPP.py"], "removed"=>nil}], "total_commits_count"=>3, "repository"=>{"name"=>"dsmes", "url"=>"git@192.168.31.100:root/dsmes.git", "description"=>"", "homepage"=>"http://192.168.31.100:9000/gitlab/root/dsmes", "git_http_url"=>"http://192.168.31.100:9000/gitlab/root/dsmes.git", "git_ssh_url"=>"git@192.168.31.100:root/dsmes.git", "visibility_level"=>0}, "repository_name"=>"dsmes", "repository_namespace"=>"root", "key"=>"cH59MpLdvdCy2Yfk1dIF"}
