### ISSUE TITLE
Gitlab called redmin, but redmine update repo fails

### ISSUE THREAD

**Issue by robinhli** [phlegx/redmine_gitlab_hook#42]
I saw the log file production.log at redmine, the related as below:
what's the issue, should I setup the username/password for it? how?

Started HEAD "/projects/dsmes" for 192.168.31.100 at 2018-05-30 17:05:53 +0800
Processing by ProjectsController#show as HTML
  Parameters: {"id"=>"dsmes"}
  Current user: anonymous
Redirected to http://192.168.31.100:7000/login?back_url=http%3A%2F%2F192.168.31.100%3A7000%2Fprojects%2Fdsmes
Filter chain halted as :authorize rendered or redirected
Completed 302 Found in 274ms (ActiveRecord: 8.1ms)

**Comment by phlegx** [comment]
@robinhli is your problem solved? Meanwhile i close the issue. Please re-open the issue if your problem persist.
