### ISSUE TITLE
 Is there a plan to adapt to 4.0?

### ISSUE THREAD

**Issue by zhongw** [phlegx/redmine_gitlab_hook#45]
As we know, Redmine 4.0 was released on 9/12 laste year, may I ask is there a plan to adapt to 4.0?
thanks

**Comment by DarkMagic** [comment]
Is this repo dropped? Anyone can support? I don't now Ruby.

**Comment by phlegx** [comment]
At the moment we don't have the time. We accept PR if someone can help.

**Comment by phlegx** [comment]
@ zhongw @DarkMagic please check out new release v4.0.0!
