### ISSUE TITLE
bitnami-redmine-4.0.2 error

### ISSUE THREAD

**Issue by xiaogangfighting** [phlegx/redmine_gitlab_hook#47]
[ 2019-03-22 17:32:51.2315 14877/7f755ef28700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /opt/redmine/apps/redmine/htdocs/: An error occurred while starting up the preloader.
  Error ID: 592d668d
  Error details saved to: /tmp/passenger-error-2x6aki.html
  Message from application: undefined method `skip_before_filter' for GitlabHookController:Class
Did you mean?  skip_before_action (NoMethodError)
  /opt/redmine/apps/redmine/htdocs/plugins/redmine_gitlab_hook/app/controllers/gitlab_hook_controller.rb:6:in `<class:GitlabHookController>'
  /opt/redmine/apps/redmine/htdocs/plugins/redmine_gitlab_hook/app/controllers/gitlab_hook_controller.rb:3:in `<top (required)>'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:378:in `block in require_or_load'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:37:in `block in load_interlock'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2/lib/active_support/dependencies/interlock.rb:13:in `loading'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:37:in `load_interlock'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:356:in `require_or_load'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:334:in `depend_on'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:246:in `require_dependency'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/engine.rb:477:in `each'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/engine.rb:477:in `block in eager_load!'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/engine.rb:475:in `each'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/engine.rb:475:in `eager_load!'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/engine.rb:356:in `eager_load!'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/application/finisher.rb:69:in `each'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
  /opt/redmine/ruby/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
  /opt/redmine/ruby/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /opt/redmine/ruby/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /opt/redmine/ruby/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /opt/redmine/ruby/lib/ruby/2.4.0/tsort.rb:347:in `each'
  /opt/redmine/ruby/lib/ruby/2.4.0/tsort.rb:347:in `call'
  /opt/redmine/ruby/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
  /opt/redmine/ruby/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
  /opt/redmine/ruby/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
  /opt/redmine/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
  /opt/redmine/apps/redmine/htdocs/config.ru:3:in `require'
  /opt/redmine/apps/redmine/htdocs/config.ru:3:in `block in <main>'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
  /opt/redmine/apps/redmine/htdocs/config.ru:1:in `new'
  /opt/redmine/apps/redmine/htdocs/config.ru:1:in `<main>'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/passenger-5.1.2/src/helper-scripts/rack-preloader.rb:110:in `eval'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/passenger-5.1.2/src/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/passenger-5.1.2/src/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/passenger-5.1.2/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /opt/redmine/ruby/lib/ruby/gems/2.4.0/gems/passenger-5.1.2/src/helper-scripts/rack-preloader.rb:29:in `<main>'

**Comment by phlegx** [comment]
@xiaogangfighting please check out new release v4.0.0!
